default['jboss']['source'] = "http://10.6.87.142/jboss-eap-6.4.0.zip"
default['jboss']['path'] = "/home/vagrant/jboss"
default['jboss']['file'] = "jboss-eap-6.4.0.zip"
default['jboss']['listen_ip'] = "192.168.33.10"
default['app']['source'] = "http://www.cumulogic.com/download/Apps/testweb.zip"
default['app']['path'] = "/home/vagrant/jboss/jboss-eap-6.4/standalone/deployments/testweb"
default['app']['file'] = "testweb.zip"